image: ubuntu

version: 0.0.{build}

# Skipping commits affecting these files.
skip_commits:
  files:
    - '**/*.README.*'
    - '**/*.md'
    - '**/*.png'
    - '**/*.ico'
    - '**/*.svg'

init:
    # Enable and get SSH details for the current build worker.
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
  - ps: | 
        if($isWindows) {
            # Enable and get SSH details for the current build worker.
            # Start-Process -FilePath "curl" -ArgumentList "-sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh'" -NoNewWindow -Wait
        # } else {
            # Enable and get RDP details for the current build worker.
            iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
        }
  - ps: |
        Write-Host -ForegroundColor White -BackgroundColor Blue ("Hello " + $env:APPVEYOR_ACCOUNT_NAME)
        Write-Host -ForegroundColor White -BackgroundColor Blue "Hope you're having great day."
        Write-Host -ForegroundColor White -BackgroundColor Blue "You're viewing project $env:APPVEYOR_PROJECT_NAME by $env:APPVEYOR_REPO_COMMIT_AUTHOR ($env:APPVEYOR_REPO_NAME) at "$env:APPVEYOR_REPO_COMMIT" ("$env:APPVEYOR_REPO_COMMIT_MESSAGE")."
    # Carriage returns can be bad
  - git config --global core.autocrlf input

# set clone depth
# XXX - this may back-fire...
clone_depth: 1

environment:
  global:
    APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtHa+G41r2gfRY+NTJrGxcpwpLZIfh4YBcaFumGgYMhJmEj1qB4Gb3ZO6ov+BegpcRlXPBYPnRmlUr2fbTs+Pkw4TxyISaVy4SPBDIpAH+dLMrYiPkLbMTCtxdYwvIlYqBMmMNNo0EGbcDwHDtlS56gZ8rjhJXd+M+we1o8+3ekEIWs9Gb5r9olJaCNsz9rfEnschWDvHEYVOJACDMbGXcEd5HdMhkzUTRPBhrfgZxMZfXLtUPjrNYp0ocKmrziesMb4dhGUXS6ZDTgponnXYD9bizz2rm+2+eGmiD10XxKoWXy+5TvAor4Y+abpmaIdGLLZBvPv+bRswZQcKjPzub Ali@CALCULON
  # If set to true SSH connection details will be displayed and the build will continue;
  # otherwise SSH details will be displayed and the build will block until ~/build.lock is deleted.
    APPVEYOR_SSH_BLOCK: false
  # Make debconf use a frontend that expects no interactive input at all,
  # preventing it from even trying to access stdin
    # Uncomment to disables execution of PowerShell commands on Linux-based
    # images. I wouldn't blame you if you did.
    # APPVEYOR_YML_DISABLE_PS_LINUX: true
    # Update the cache even if build fails
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    USE_CCACHE: 1
    ANDROID_JACK_VM_ARGS: "-Xmx8g -Dfile.encoding=UTF-8 -XX:+TieredCompilation"
    DEBIAN_FRONTEND: noninteractive

# matrix:
  # Immediately finish build if any job fails.
  # XXX - disabled for now
  # fast_finish: true

cache:
  - android/lineage -> **\rebuild.cache      # preserve "LOS16" directory in the root of build folder but will reset it if rebuild.cache is modified
  # - android/lineage -> appveyor.yml


# The build won't be considered failed if anything fails here.
install:
  - sh: printf "Linux FTW!\n"
  - ps: |
        if($isLinux) {
            if($env:CMAKE_LINT) {
                Write-Host -ForegroundColor Black -BackgroundColor Green "This is cmake-lint!"
                git clone https://github.com/richq/cmake-lint.git
                if(test-path cmake-lint) {
                    cd cmake-lint
                } else {
                    throw "Error while cloning (or changing directory to) 'cmake-lint'."
                }
                sudo python setup.py install
                cd ..
            } else {
                Write-Host -ForegroundColor Black -BackgroundColor Green "This is Linux!"
                sudo apt-get -qq update
                # sudo apt-get -qq upgrade
                sudo apt-get install -qq openjdk-8-jdk android-tools-adb bc curl flex g++-multilib gcc-multilib gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2-utils lzop pngcrush schedtool xsltproc yasm repo
            }
        } else {
            Write-Host -ForegroundColor Black -BackgroundColor Green "This is NOT Linux!"
            if($env:GEN -match "Visual Studio 15 2017") {
                Write-Host -ForegroundColor Black -BackgroundColor Green "Visual Studio 15 2017!"
                vcpkg update
                vcpkg install openssl zlib pthreads winpcap
            } else {
                Write-Host -ForegroundColor Black -BackgroundColor Green "MinGW$env:ARCH!"
                # .\contrib\InstallNpcap.ps1
                Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://github.com/sgeto/InstallNpcap/raw/master/InstallNpcap.ps1'))
            }
        }
  # Clone the submodules.
  - git submodule update --init --recursive
  - sh: ./cache.sh

before_build:
  - ps: |
        if($isLinux) {
            if($env:CMAKE_LINT) {
                Write-Host -ForegroundColor Black -BackgroundColor Green "This is cmake-lint!"
            } else {
                Write-Host -ForegroundColor Black -BackgroundColor Green "This is Linux!"
                Start-Process -FilePath "uname" -ArgumentList "-a" -NoNewWindow -Wait
                Write-Host -ForegroundColor Black -BackgroundColor Green "No `$PATH stuff yet..."
            }
        } else {
            Write-Host -ForegroundColor Black -BackgroundColor Green "This is NOT Linux!"
            $env:path += ";C:\msys64\mingw$env:ARCH\bin;C:\msys64\usr\bin"
        }
  - sh: source build/envsetup.sh
  # - sh: lineage_i9300-userdebug
  - sh: lineage_i9300-eng

build_script:
  - sh: croot
  - sh: brunch bacon > $HOME/buildlog.log 2>&1

# Push build logs as artifacts even (or especially) in case of a build failure
on_failure:
  # - ps: |
        # Push-AppveyorArtifact "android/lineage"
  - sh: df -h
  - sh: free -g
  - ps: |
        # Enable this only when the build was executed by the "RE-BUILD COMMIT"
        # button on the AppVeyor web interface.
        if($env:APPVEYOR_RE_BUILD) {
            if($isLinux) {
                # To investigate worker via SSH on build failure, pause/block the
                # build until either ~/build.lock is deleted and/or the overall
                # build time (60 min) is exceeded.
                Set-AppveyorBuildVariable -Name APPVEYOR_SSH_BLOCK -Value $true
            } else {
                # To investigate worker via RDP on build failure, pause the build
                # until a special “lock” file on the VM desktop is deleted and/or
                # the overall build time (60 min) is exceeded.
                $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
            }
        }

artifacts:
  - path: 'android/lineage'
    name: lineage
    type: zip
  - path: '**\*.log'
    name: logs
  - path: 'out'
    name: out
    type: zip

# XXX - add AppVeyor bot
# XXX - add IRC
# XXX - can I post on twitter/mailing list if build succeed?
# template files to use: https://www.appveyor.com/docs/notifications/#webhook-payload-default
# https://stackoverflow.com/questions/47757094/notification-templating-with-webhooks-default-payload-appveyor
notifications:
  - provider: Email
    to:
    - '{{commitAuthorEmail}}'
    # - ettercap-users@lists.ettercap-project.org
    subject: 'Build {{status}}'              
    message: "Build {{projectName}} {{buildVersion}} {{status}}: {{buildUrl}}
    Commit #{{commitId}} by {{commitAuthor}} on {{commitDate}}: {{commitMessage}}
    Random Eventdata follows
    Duration {{duration}}
    Repository Name {{repositoryName}}
    Branch {{branch}}
    Commit Author Email {{commitAuthorEmail}}
    Commit Message {{commitMessage}}
    Commit Message Extended {{commitMessageExtended}}
    Commit is Pull-Request {{isPullRequest}}
    Build Messages {{messages}}
    <p>Artifacts</p>
    <ul>
    {{#jobs}}
      {{#artifacts}}
        <li>{{url}}</li>
      {{/artifacts}}
    {{/jobs}}
    </ul>"
    on_build_success: true # for now
    on_build_failure: true # for now
    on_build_status_changed: true
  # - provider: GitHubPullRequest
    # auth_token:
      # secure: VwyaJwle6Sl0AuOebFpGCIXiPyC2aOZjH0MZe+i8YlFib7AcqvDkbZQUqKbVuHK5
    # template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
